In [22]:
import json
import glob
import os
from pathlib import Path
import numpy as np
import cv2
import copy
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import display

In [2]:
# data_root_path = Path('/root/synthetic_cabin_1m/syntheticcabin_1mil/SyntheticCabin_1m/masks')
# folders = [item for item in data_root_path.iterdir() if item.is_dir()]
# for folder in folders:
#     print(folder)

In [3]:
# !ls /root/synthetic_cabin_1m/syntheticcabin_1mil/SyntheticCabin_1m

In [4]:
!ls /root/synthetic_cabin_1m/

lost+found  syntheticcabin_1mil

In [5]:
data_root_path = Path('/root/synthetic_cabin_1m/syntheticcabin_1mil/SyntheticCabin_1m/')
raw_annotation_folder = data_root_path / 'gt_jsons_2'
output_annotation_folder = data_root_path / 'gt_jsons'

all_files = set(raw_annotation_folder.iterdir())
# all_files = [f.stem.split('_')[1] for f in raw_annotation_folder.iterdir()]
processed_files = set([f.name for f in output_annotation_folder.iterdir()])
remaining_files = all_files.difference(processed_files)

In [6]:
# img_id = '703666'
# img = cv2.imread(f'/root/synthetic_cabin_1m/syntheticcabin_1mil/SyntheticCabin_1m/images/frame_{img_id}.jpg')
# img = cv2.imread(all_files[0].as_posix())
# imgplot = plt.imshow(img)

In [7]:
# img_id = '703666'
# mask_img = cv2.imread(f'/root/synthetic_cabin_1m/syntheticcabin_1mil/SyntheticCabin_1m/masks/mask_{img_id}.png')
# imgray = cv2.cvtColor(mask_img, cv2.COLOR_BGR2GRAY)
# ret, thresh = cv2.threshold(imgray, 75, 255, 0)
# contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
# cv2.drawContours(mask_img, contours, -1, (255, 255, 255), 3)
# # print(len(contours))
# # x,y,w,h = cv2.boundingRect(contours[0])
# if len(contours) == 0:
#     print('coutours is empty')
# else:
#     x,y,w,h = cv2.boundingRect(np.vstack(contours))
#     img = cv2.rectangle(mask_img,(x,y),(x + w,y + h),(0,255,0),2)
#     imgplot = plt.imshow(img)

#     img = cv2.imread(f'/root/synthetic_cabin_1m/syntheticcabin_1mil/SyntheticCabin_1m/images/frame_{img_id}.jpg')
#     print(x, y, w, h)
#     img = cv2.rectangle(img,(x,y),(x + w,y + h),(0,255,0),2)
#     imgplot = plt.imshow(img)

In [8]:
# import json


# def get_bbox(filename):
#     img = cv2.imread(filename)
#     imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#     ret, thresh = cv2.threshold(imgray, 75, 255, 0)
#     contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
#     if len(contours) > 0:
#         x,y,w,h = cv2.boundingRect(np.vstack(contours))
#         return x, y, w, h
#     else:
#         return 0, 0, 0, 0

In [9]:
# characters = {}
# file_size = {}
# count = len(processed_files)
# count_all_files = len(all_files)
# print(f'processed: {count} / {count_all_files} = {(count / count_all_files):.4f}.')
# len(remaining_files)
# # with annotation_folder.open() as f:
# for file_name in iter(remaining_files):
#     with (raw_annotation_folder / file_name).open() as i:
#         info = json.load(i)
#         img_name = info['img_name']
#         img_id = img_name.split('.')[0].split('_')[1]
#         mask_img = (data_root_path / 'masks' / f'mask_{img_id}.png').as_posix()
#         try:
#             bbox = get_bbox(mask_img)
#         except:
#             print(f'error at {img_name}')
#             break
#         area = bbox[2] * bbox[3]
#         file_size[img_id] = area
#         # if area < 1000:
#             # print(f'{img_name} has an area of {area}')
#             # continue
#         info['humans'][0]['full_body_bbox'] = {
#             'x': bbox[0],
#             'y': bbox[1],
#             'width': bbox[2],
#             'height': bbox[3],
#             'bbox_area': area
#         }
        
#         with (output_annotation_folder / f'gt_{img_id}.json').open('w') as f:
#             json.dump(info, f, indent=2)
#         count += 1
#     if count % 10000 == 0:
#         print(f'processed: {count} / {count_all_files} = {(count / count_all_files):.4f}.')
# print('finish')

In [10]:
# count = len(processed_files)
count = 0
count_all_files = len(all_files)
stats = []
# print(f'processed: {count} / {count_all_files} = {(count / count_all_files):.4f}.')
len(remaining_files)
# with annotation_folder.open() as f:
for file_name in iter(all_files):
    with (raw_annotation_folder / file_name).open() as i:
        info = json.load(i)
        img_name = info['img_name']
        img_id = img_name.split('.')[0].split('_')[1]
        item = {
            'name': info['humans'][0]['name'],
            'camera_pose': info['camera_parameters']['name'],
            'environment_name': info['experiments_meta_data']['environment_name']
        }
        stats.append(item)
        count += 1
    if count % 10000 == 0:
        print(f'processed: {count} / {count_all_files} = {(count / count_all_files):.4f}.')
print('finish')

processed: 10000 / 964725 = 0.0104.
processed: 20000 / 964725 = 0.0207.
processed: 30000 / 964725 = 0.0311.
processed: 40000 / 964725 = 0.0415.
processed: 50000 / 964725 = 0.0518.
processed: 60000 / 964725 = 0.0622.
processed: 70000 / 964725 = 0.0726.
processed: 80000 / 964725 = 0.0829.
processed: 90000 / 964725 = 0.0933.
processed: 100000 / 964725 = 0.1037.
processed: 110000 / 964725 = 0.1140.
processed: 120000 / 964725 = 0.1244.
processed: 130000 / 964725 = 0.1348.
processed: 140000 / 964725 = 0.1451.
processed: 150000 / 964725 = 0.1555.
processed: 160000 / 964725 = 0.1659.
processed: 170000 / 964725 = 0.1762.
processed: 180000 / 964725 = 0.1866.
processed: 190000 / 964725 = 0.1969.
processed: 200000 / 964725 = 0.2073.
processed: 210000 / 964725 = 0.2177.
processed: 220000 / 964725 = 0.2280.
processed: 230000 / 964725 = 0.2384.
processed: 240000 / 964725 = 0.2488.
processed: 250000 / 964725 = 0.2591.
processed: 260000 / 964725 = 0.2695.
processed: 270000 / 964725 = 0.2799.
processed: 280000 / 964725 = 0.2902.
processed: 290000 / 964725 = 0.3006.
processed: 300000 / 964725 = 0.3110.
processed: 310000 / 964725 = 0.3213.
processed: 320000 / 964725 = 0.3317.
processed: 330000 / 964725 = 0.3421.
processed: 340000 / 964725 = 0.3524.
processed: 350000 / 964725 = 0.3628.
processed: 360000 / 964725 = 0.3732.
processed: 370000 / 964725 = 0.3835.
processed: 380000 / 964725 = 0.3939.
processed: 390000 / 964725 = 0.4043.
processed: 400000 / 964725 = 0.4146.
processed: 410000 / 964725 = 0.4250.
processed: 420000 / 964725 = 0.4354.
processed: 430000 / 964725 = 0.4457.
processed: 440000 / 964725 = 0.4561.
processed: 450000 / 964725 = 0.4665.
processed: 460000 / 964725 = 0.4768.
processed: 470000 / 964725 = 0.4872.
processed: 480000 / 964725 = 0.4976.
processed: 490000 / 964725 = 0.5079.
processed: 500000 / 964725 = 0.5183.
processed: 510000 / 964725 = 0.5286.
processed: 520000 / 964725 = 0.5390.
processed: 530000 / 964725 = 0.5494.
processed: 540000 / 964725 = 0.5597.
processed: 550000 / 964725 = 0.5701.
processed: 560000 / 964725 = 0.5805.
processed: 570000 / 964725 = 0.5908.
processed: 580000 / 964725 = 0.6012.
processed: 590000 / 964725 = 0.6116.
processed: 600000 / 964725 = 0.6219.
processed: 610000 / 964725 = 0.6323.
processed: 620000 / 964725 = 0.6427.
processed: 630000 / 964725 = 0.6530.
processed: 640000 / 964725 = 0.6634.
processed: 650000 / 964725 = 0.6738.
processed: 660000 / 964725 = 0.6841.
processed: 670000 / 964725 = 0.6945.
processed: 680000 / 964725 = 0.7049.
processed: 690000 / 964725 = 0.7152.
processed: 700000 / 964725 = 0.7256.
processed: 710000 / 964725 = 0.7360.
processed: 720000 / 964725 = 0.7463.
processed: 730000 / 964725 = 0.7567.
processed: 740000 / 964725 = 0.7671.
processed: 750000 / 964725 = 0.7774.
processed: 760000 / 964725 = 0.7878.
processed: 770000 / 964725 = 0.7982.
processed: 780000 / 964725 = 0.8085.
processed: 790000 / 964725 = 0.8189.
processed: 800000 / 964725 = 0.8293.
processed: 810000 / 964725 = 0.8396.
processed: 820000 / 964725 = 0.8500.
processed: 830000 / 964725 = 0.8603.
processed: 840000 / 964725 = 0.8707.
processed: 850000 / 964725 = 0.8811.
processed: 860000 / 964725 = 0.8914.
processed: 870000 / 964725 = 0.9018.
processed: 880000 / 964725 = 0.9122.
processed: 890000 / 964725 = 0.9225.
processed: 900000 / 964725 = 0.9329.
processed: 910000 / 964725 = 0.9433.
processed: 920000 / 964725 = 0.9536.
processed: 930000 / 964725 = 0.9640.
processed: 940000 / 964725 = 0.9744.
processed: 950000 / 964725 = 0.9847.
processed: 960000 / 964725 = 0.9951.
finish

In [12]:
stat_df = pd.DataFrame.from_records(stats)

In [30]:
stat_df.groupby('name').count().index.shape

(16,)

In [31]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(stat_df[stat_df['camera_pose'] == 'A_Pillar_Codriver'].groupby(['name', 'camera_pose']).count())

                           environment_name
name    camera_pose
Alison  A_Pillar_Codriver              9375
Amit    A_Pillar_Codriver              9375
Carla   A_Pillar_Codriver              9375
Claudia A_Pillar_Codriver              9375
Cody    A_Pillar_Codriver              9375
Debra   A_Pillar_Codriver              9375
Ellie   A_Pillar_Codriver              9375
Eric    A_Pillar_Codriver              9375
Karl    A_Pillar_Codriver              9375
Kyle    A_Pillar_Codriver              9375
Megan   A_Pillar_Codriver              9375
Mira    A_Pillar_Codriver              9375
Otto    A_Pillar_Codriver              9375
Ryo     A_Pillar_Codriver              8474
Seiko   A_Pillar_Codriver              6250
Tyrone  A_Pillar_Codriver              6250

In [32]:
stat_df[stat_df['camera_pose'] == 'A_Pillar_Codriver'].groupby(['name', 'camera_pose']).count().sum()

environment_name    142849
dtype: int64

In [19]:
stat_df.groupby('camera_pose').count()

                     name  environment_name
camera_pose
A_Pillar_Codriver  142849            142849
A_Pillar_Driver    143750            143750
Dashboard          143750            143750
Front               50000             50000
Front_Left          50000             50000
Front_Right         50000             50000
Front_TopLeft       50000             50000
Front_TopRight      50000             50000
OMS_01             143751            143751
Rear_Mirror        140625            140625

In [20]:
stat_df.groupby('environment_name').count()

                    name  camera_pose
environment_name
Audi              250001       250001
Empty             250000       250000
Mazda             250000       250000
Porsche           214724       214724